export const Employees = [
  {
    id: '1',
    name: 'Thomas Hardy',
    email: '	thomashardy@mail.com',
    address: '	89 Chiaroscuro Rd, Portland, USA',
    phone: '(171) 555-2222',
  },
  {
    id: '2',
    name: 'Dominique Perrier',
    email: 'dominiqueperrier@mail.com',
    address: 'Obere Str. 57, Berlin, Germany',
    phone: '(313) 555-5735',
  },
  {
    id: '3',
    name: 'Thomas Hardy',
    email: '	thomashardy@mail.com',
    address: '	89 Chiaroscuro Rd, Portland, USA',
    phone: '(171) 555-2222',
  },
  {
    id: '4',
    name: 'Thomas Hardy',
    email: '	thomashardy@mail.com',
    address: '	89 Chiaroscuro Rd, Portland, USA',
    phone: '(171) 555-2222',
  },
  {
    id: '5',
    name: 'Thomas Hardy',
    email: '	thomashardy@mail.com',
    address: '	89 Chiaroscuro Rd, Portland, USA',
    phone: '(171) 555-2222',
  },
  {
    id: '6',
    name: 'Dominique Perrier',
    email: 'dominiqueperrier@mail.com',
    address: 'Obere Str. 57, Berlin, Germany',
    phone: '(313) 555-5735',
  },
  {
    id: '7',
    name: 'Dominique Perrier',
    email: 'dominiqueperrier@mail.com',
    address: 'Obere Str. 57, Berlin, Germany',
    phone: '(313) 555-5735',
  },
  {
    id: '8',
    name: 'Dominique Perrier',
    email: 'dominiqueperrier@mail.com',
    address: 'Obere Str. 57, Berlin, Germany',
    phone: '(313) 555-5735',
  },
];
