export const Employees = [
  {
    id: '01',
    name: 'Thomas Hardy',
    email: '	thomashardy@mail.com',
    address: '	89 Chiaroscuro Rd, Portland, USA',
    phone: '(171) 555-2222',
  },
  {
    id: '02',
    name: 'Dominique Perrier',
    email: 'dominiqueperrier@mail.com',
    address: 'Obere Str. 57, Berlin, Germany',
    phone: '(313) 555-5735',
  },
  {
    id: '03',
    name: 'Thomas Hardy',
    email: '	thomashardy@mail.com',
    address: '	89 Chiaroscuro Rd, Portland, USA',
    phone: '(171) 555-2222',
  },
  {
    id: '04',
    name: 'Thomas Hardy',
    email: '	thomashardy@mail.com',
    address: '	89 Chiaroscuro Rd, Portland, USA',
    phone: '(171) 555-2222',
  },
  {
    id: '05',
    name: 'Thomas Hardy',
    email: '	thomashardy@mail.com',
    address: '	89 Chiaroscuro Rd, Portland, USA',
    phone: '(171) 555-2222',
  },
  {
    id: '06',
    name: 'Dominique Perrier',
    email: 'dominiqueperrier@mail.com',
    address: 'Obere Str. 57, Berlin, Germany',
    phone: '(313) 555-5735',
  },
  {
    id: '07',
    name: 'Dominique Perrier',
    email: 'dominiqueperrier@mail.com',
    address: 'Obere Str. 57, Berlin, Germany',
    phone: '(313) 555-5735',
  },
  {
    id: '08',
    name: 'Dominique Perrier',
    email: 'dominiqueperrier@mail.com',
    address: 'Obere Str. 57, Berlin, Germany',
    phone: '(313) 555-5735',
  },
];
